# @file mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/stfwi/engineers-decor/issues/"
license="MIT"

[[mods]]
modId="engineersdecor"
version="${file.jarVersion}"
displayName="Engineer's Decor"
description="Adds cosmetic blocks for the engineer's workshop, factory and home."
authors="wilechaote"
credits="BluSunrize, Damien Hazard, malte0811, et al., the Forge Smiths."
updateJSONURL="https://raw.githubusercontent.com/stfwi/engineers-decor/versions/1.19.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/engineers-decor"
logoFile="logo.png"

[[dependencies.engineersdecor]]
  modId="forge"
  mandatory=true
  versionRange="[41.1.0,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.engineersdecor]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.19,1.20)"
  ordering="NONE"
  side="BOTH"
