# @file mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
modLoader="javafml" # forge FML java
loaderVersion="[25,)"
issueTrackerURL="https://github.com/stfwi/engineers-decor/issues/"

[[mods]]

modId="engineersdecor"
version="${file.jarVersion}"
displayName="Engineer's Decor"
description="Adds cosmetic blocks for the engineer's workshop, factory and home."
authors="wilechaote"
credits="BluSunrize, malte0811, et al., the Forge Smiths, the Modders of the World."
updateJSONURL="https://raw.githubusercontent.com/stfwi/engineers-decor/develop/meta/update.json"
displayURL="https://github.com/stfwi/engineers-decor/"
logoFile="engineersdecor.png"   # Double check: A file name (in the root of the mod JAR) containing a logo for display

[[dependencies.engineersdecor]]
  modId="forge"
  mandatory=true
  versionRange="[25,)" #mandatory
  ordering="NONE"
  side="BOTH"

[[dependencies.engineersdecor]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.13.2]"
  ordering="NONE"
  side="BOTH"
